"""Multi-reference source face selector.

Analyzes the live webcam frame's lighting and head pose each frame, then
selects (or blends) the best-matching source face variant from a pre-built
library.  This eliminates lighting mismatch — the single biggest remaining
artifact when using a static source face in changing environments.

Variant library layout:
    source_faces/
    ├── identity.json          # metadata (auto-generated by generate_source_faces.py)
    ├── front_neutral.png
    ├── front_warm.png
    ├── left_15.png
    └── ...

If identity.json is absent the selector auto-detects variant properties
from the images themselves — users can create variants manually in any
image tool and just drop them in the directory.

Runtime cost: < 2ms per frame for select() with up to 16 variants.
"""

from __future__ import annotations

import copy
import glob
import json
import logging
import os
import time
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import cv2
import numpy as np

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Variant dataclass
# ---------------------------------------------------------------------------

@dataclass
class SourceVariant:
    """One source face variant with its measured/estimated properties."""
    image: np.ndarray                         # BGR face image
    face: object                              # insightface Face object
    embedding: np.ndarray                     # 512-d normed ArcFace
    pose_yaw: float = 0.0                     # head yaw in degrees (-90…+90)
    pose_pitch: float = 0.0                   # head pitch in degrees
    color_temperature: float = 5500.0         # estimated Kelvin
    lighting_direction: np.ndarray = field(
        default_factory=lambda: np.zeros(2, dtype=np.float32))
    mean_luminance: float = 0.5               # [0, 1]
    mean_lab_color: np.ndarray = field(
        default_factory=lambda: np.array([128.0, 128.0, 128.0]))
    filename: str = ""
    identity_similarity: float = 1.0         # cosine sim vs base embedding


# ---------------------------------------------------------------------------
# SourceFaceSelector
# ---------------------------------------------------------------------------

class SourceFaceSelector:
    """Runtime selector: picks or blends source face variants per frame.

    Args:
        swapper:        NeuralFaceSwapper instance (for face detection)
        config:         dict with optional keys from config/default.yaml
            source_face_dir     path to variants directory
            method              'select' or 'blend' (default 'select')
            pose_weight         (default 3.0)
            temperature_weight  (default 2.0)
            direction_weight    (default 1.5)
            luminance_weight    (default 1.0)
            switch_threshold    (default 0.15 — 15% improvement needed)
            switch_delay_frames (default 5)
    """

    _IMAGE_EXTS = ("*.png", "*.jpg", "*.jpeg", "*.bmp", "*.webp",
                   "*.PNG", "*.JPG", "*.JPEG", "*.BMP", "*.WEBP")

    def __init__(self, swapper, config: dict):
        self._swapper = swapper
        cfg = config

        self.method              = str(cfg.get("method",              "select"))
        self.pose_weight         = float(cfg.get("pose_weight",       3.0))
        self.temperature_weight  = float(cfg.get("temperature_weight", 2.0))
        self.direction_weight    = float(cfg.get("direction_weight",   1.5))
        self.luminance_weight    = float(cfg.get("luminance_weight",   1.0))
        self.switch_threshold    = float(cfg.get("switch_threshold",   0.15))
        self.switch_delay_frames = int(cfg.get("switch_delay_frames",  5))

        self.variants: List[SourceVariant] = []
        self._current_idx: Optional[int] = None
        self._pending_idx: Optional[int] = None
        self._pending_count: int = 0

        source_dir = str(cfg.get("source_face_dir", "source_faces"))
        self._load_variants(source_dir)

        if not self.variants:
            raise FileNotFoundError(
                f"No valid source face variants found in: {source_dir}"
            )
        print(f"[SourceFaceSelector] Loaded {len(self.variants)} variants "
              f"(method={self.method})")

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def _load_variants(self, directory: str) -> None:
        paths: List[str] = []
        for ext in self._IMAGE_EXTS:
            paths.extend(glob.glob(os.path.join(directory, ext)))
        paths = sorted(set(paths))

        # Load metadata if available
        meta: dict = {}
        meta_path = os.path.join(directory, "identity.json")
        if os.path.exists(meta_path):
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            log.info(f"[Selector] Loaded identity.json from {directory}")

        meta_by_file: dict = {}
        for entry in meta.get("variants", []):
            meta_by_file[entry["filename"]] = entry

        base_emb: Optional[np.ndarray] = (
            np.array(meta["identity_embedding"], dtype=np.float32)
            if "identity_embedding" in meta else None
        )

        for path in paths:
            fname = os.path.basename(path)
            img = cv2.imread(path)
            if img is None:
                log.warning(f"[Selector] Cannot read {path} — skipped")
                continue

            faces = self._swapper.detect(img)
            if not faces:
                log.warning(f"[Selector] No face in {path} — skipped")
                continue

            face = faces[0]
            emb = face.normed_embedding.astype(np.float32).copy()

            # Identity verification
            sim = 1.0
            if base_emb is not None:
                sim = float(np.dot(emb, base_emb) /
                            (np.linalg.norm(emb) * np.linalg.norm(base_emb) + 1e-8))
                if sim < 0.5:
                    log.warning(f"[Selector] {fname} identity sim={sim:.2f} < 0.5 — skipped")
                    continue

            variant = SourceVariant(
                image=img,
                face=face,
                embedding=emb,
                filename=fname,
                identity_similarity=sim,
            )

            if fname in meta_by_file:
                m = meta_by_file[fname]
                variant.pose_yaw          = float(m.get("pose_yaw", 0.0))
                variant.pose_pitch        = float(m.get("pose_pitch", 0.0))
                variant.color_temperature = float(m.get("lighting_temperature", 5500.0))
                ld = m.get("lighting_direction", [0.0, 0.0])
                variant.lighting_direction = np.array(ld, dtype=np.float32)
                variant.mean_luminance    = float(m.get("lighting_intensity", 0.5))
            else:
                self._auto_detect_properties(variant)

            self.variants.append(variant)
            log.info(f"[Selector] {fname}  yaw={variant.pose_yaw:+.0f}°  "
                     f"T={variant.color_temperature:.0f}K  sim={variant.identity_similarity:.2f}")

    def _auto_detect_properties(self, variant: SourceVariant) -> None:
        """Infer pose/lighting from the variant image itself (no metadata needed)."""
        kps = variant.face.kps
        variant.pose_yaw, variant.pose_pitch = self.estimate_pose(kps)

        h, w = variant.image.shape[:2]
        # Use entire image as "face bbox" for the source variant
        bbox = np.array([0, 0, w, h], dtype=np.float32)
        t, ld, lum = self.estimate_lighting(variant.image, bbox)
        variant.color_temperature  = t
        variant.lighting_direction = ld
        variant.mean_luminance     = lum

        # Mean LAB color of face skin (used for diagnostics)
        lab = cv2.cvtColor(variant.image, cv2.COLOR_BGR2LAB)
        variant.mean_lab_color = np.mean(lab.reshape(-1, 3), axis=0)

    # ------------------------------------------------------------------
    # Pose estimation from 5-point landmarks
    # ------------------------------------------------------------------

    def estimate_pose(self, kps: np.ndarray) -> Tuple[float, float]:
        """Estimate head yaw and pitch from 5-point face landmarks.

        Landmark order (InsightFace convention):
            0 = left eye, 1 = right eye, 2 = nose tip,
            3 = left mouth corner, 4 = right mouth corner

        Args:
            kps: (5, 2) array of (x, y) landmark positions

        Returns:
            (yaw_deg, pitch_deg)
        """
        if kps is None or len(kps) < 5:
            return 0.0, 0.0

        left_eye  = kps[0].astype(np.float32)
        right_eye = kps[1].astype(np.float32)
        nose      = kps[2].astype(np.float32)
        left_mouth  = kps[3].astype(np.float32)
        right_mouth = kps[4].astype(np.float32)

        # --- Yaw ---
        eye_center   = (left_eye + right_eye) / 2.0
        eye_dist     = float(np.linalg.norm(right_eye - left_eye)) + 1e-6
        # Nose displacement relative to inter-eye midpoint, normalised by eye width
        nose_offset_x = float(nose[0] - eye_center[0])
        yaw_ratio     = nose_offset_x / eye_dist
        yaw_deg = float(np.degrees(np.arcsin(np.clip(yaw_ratio * 2.0, -1.0, 1.0))))

        # --- Pitch ---
        mouth_center  = (left_mouth + right_mouth) / 2.0
        face_vertical = float(mouth_center[1] - eye_center[1]) + 1e-6
        nose_vertical = float(nose[1] - eye_center[1])
        pitch_ratio   = nose_vertical / face_vertical
        # Neutral ratio ≈ 0.35 (nose sits 35% of the way from eyes to mouth)
        pitch_deg = (pitch_ratio - 0.35) * 90.0

        return float(yaw_deg), float(pitch_deg)

    # ------------------------------------------------------------------
    # Lighting estimation
    # ------------------------------------------------------------------

    def estimate_lighting(
        self,
        frame: np.ndarray,
        face_bbox: np.ndarray,
    ) -> Tuple[float, np.ndarray, float]:
        """Estimate color temperature, light direction and luminance.

        Args:
            frame:     BGR frame
            face_bbox: (x1, y1, x2, y2) face bounding box

        Returns:
            (temperature_K, direction_xy, mean_luminance)
        """
        fh, fw = frame.shape[:2]
        x1, y1, x2, y2 = face_bbox[:4].astype(int)

        # Add 50% padding around bbox for richer context
        pad_x = int((x2 - x1) * 0.5)
        pad_y = int((y2 - y1) * 0.5)
        rx1 = max(0, x1 - pad_x);  rx2 = min(fw, x2 + pad_x)
        ry1 = max(0, y1 - pad_y);  ry2 = min(fh, y2 + pad_y)

        crop = frame[ry1:ry2, rx1:rx2]
        if crop.size == 0:
            return 5500.0, np.zeros(2, dtype=np.float32), 0.5

        # --- Color temperature from LAB b* channel ---
        lab = cv2.cvtColor(crop, cv2.COLOR_BGR2LAB)
        mean_b = float(np.mean(lab[:, :, 2]))   # b* axis: +yellow, -blue
        # Higher b* (yellow-biased) → warmer; lower (blue-biased) → cooler
        temperature = 3000.0 + (mean_b / 255.0) * 7000.0   # 3000–10000 K

        # --- Lighting direction from brightness asymmetry ---
        gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY).astype(np.float32)
        ch, cw = gray.shape

        # Horizontal: left vs right halves
        left_mean  = float(np.mean(gray[:, :cw // 2]))
        right_mean = float(np.mean(gray[:, cw // 2:]))
        dir_x = (right_mean - left_mean) / (right_mean + left_mean + 1e-6)

        # Vertical: top vs bottom halves
        top_mean    = float(np.mean(gray[:ch // 2, :]))
        bottom_mean = float(np.mean(gray[ch // 2:, :]))
        dir_y = (bottom_mean - top_mean) / (bottom_mean + top_mean + 1e-6)

        direction = np.array([dir_x, dir_y], dtype=np.float32)

        # --- Overall luminance ---
        luminance = float(np.mean(gray)) / 255.0

        return temperature, direction, luminance

    # ------------------------------------------------------------------
    # Scoring
    # ------------------------------------------------------------------

    def compute_match_score(
        self,
        variant: SourceVariant,
        target_yaw: float,
        target_pitch: float,
        target_temperature: float,
        target_light_dir: np.ndarray,
        target_luminance: float,
    ) -> float:
        """Score how well a variant matches current conditions (lower = better)."""
        # Pose (most important)
        yaw_diff   = abs(variant.pose_yaw   - target_yaw)
        pitch_diff = abs(variant.pose_pitch - target_pitch)
        pose_score = (yaw_diff / 45.0 + pitch_diff / 30.0) * self.pose_weight

        # Color temperature
        temp_diff  = abs(variant.color_temperature - target_temperature)
        temp_score = (temp_diff / 5000.0) * self.temperature_weight

        # Lighting direction
        dir_diff  = float(np.linalg.norm(variant.lighting_direction - target_light_dir))
        dir_score = dir_diff * self.direction_weight

        # Luminance
        lum_diff  = abs(variant.mean_luminance - target_luminance)
        lum_score = lum_diff * self.luminance_weight

        return pose_score + temp_score + dir_score + lum_score

    def _score_all(
        self,
        target_yaw: float,
        target_pitch: float,
        target_temperature: float,
        target_light_dir: np.ndarray,
        target_luminance: float,
    ) -> List[float]:
        return [
            self.compute_match_score(
                v, target_yaw, target_pitch,
                target_temperature, target_light_dir, target_luminance
            )
            for v in self.variants
        ]

    # ------------------------------------------------------------------
    # Selection with hysteresis
    # ------------------------------------------------------------------

    def _apply_hysteresis(self, scores: List[float]) -> int:
        """Return the index to use after applying hysteresis / switch delay."""
        best_idx = int(np.argmin(scores))

        if self._current_idx is None:
            self._current_idx = best_idx
            self._pending_idx = None
            self._pending_count = 0
            return best_idx

        cur_score  = scores[self._current_idx]
        best_score = scores[best_idx]

        if best_idx == self._current_idx:
            self._pending_idx   = None
            self._pending_count = 0
            return self._current_idx

        improvement = (cur_score - best_score) / (cur_score + 1e-6)
        if improvement < self.switch_threshold:
            # Not enough improvement — stay with current
            self._pending_idx   = None
            self._pending_count = 0
            return self._current_idx

        # Track consecutive frames requesting a switch
        if self._pending_idx == best_idx:
            self._pending_count += 1
        else:
            self._pending_idx   = best_idx
            self._pending_count = 1

        if self._pending_count >= self.switch_delay_frames:
            self._current_idx   = best_idx
            self._pending_idx   = None
            self._pending_count = 0
            log.debug(f"[Selector] Switched to variant {best_idx} "
                      f"({self.variants[best_idx].filename})")
        return self._current_idx

    # ------------------------------------------------------------------
    # Public API — select (pick best single variant)
    # ------------------------------------------------------------------

    def select(self, frame: np.ndarray, detected_face) -> SourceVariant:
        """Pick the best-matching source variant for the current frame.

        Args:
            frame:          BGR webcam frame
            detected_face:  insightface Face object from the detector

        Returns:
            Best-matching SourceVariant (with hysteresis).
        """
        yaw, pitch = self.estimate_pose(detected_face.kps)
        temp, ld, lum = self.estimate_lighting(frame, detected_face.bbox)

        scores = self._score_all(yaw, pitch, temp, ld, lum)
        idx    = self._apply_hysteresis(scores)
        return self.variants[idx]

    # ------------------------------------------------------------------
    # Public API — select_blended (blend top-3 embeddings)
    # ------------------------------------------------------------------

    def select_blended(
        self,
        frame: np.ndarray,
        detected_face,
    ) -> Tuple[object, np.ndarray]:
        """Blend the top-3 variants' embeddings weighted by match quality.

        Blending in ArcFace embedding space produces a smoothly interpolated
        source identity that is better-matched than any single variant.

        Args:
            frame:          BGR webcam frame
            detected_face:  insightface Face object

        Returns:
            (face_object, blended_image)
            face_object has normed_embedding replaced by the weighted blend.
        """
        yaw, pitch = self.estimate_pose(detected_face.kps)
        temp, ld, lum = self.estimate_lighting(frame, detected_face.bbox)

        scores = self._score_all(yaw, pitch, temp, ld, lum)

        # Top 3 (or fewer if not enough variants)
        k = min(3, len(self.variants))
        top_indices = np.argsort(scores)[:k].tolist()

        raw_scores = np.array([scores[i] for i in top_indices], dtype=np.float64)
        weights = 1.0 / (raw_scores + 0.01)
        weights = (weights / weights.sum()).astype(np.float32)

        # Blend embeddings in ArcFace space
        blended_emb = np.zeros(512, dtype=np.float32)
        for idx, w in zip(top_indices, weights):
            blended_emb += w * self.variants[idx].embedding
        norm = float(np.linalg.norm(blended_emb))
        if norm > 1e-8:
            blended_emb /= norm

        # Build synthetic Face object using best variant as base
        best = self.variants[top_indices[0]]
        best_face = copy.deepcopy(best.face)
        best_face.normed_embedding = blended_emb
        # Scale unnormed embedding to match original magnitude
        orig_norm = float(np.linalg.norm(best.face.embedding)) if hasattr(best.face, "embedding") else 1.0
        if hasattr(best_face, "embedding"):
            best_face.embedding = blended_emb * orig_norm

        # Blend source images for color reference in downstream stages
        blended_img = np.zeros_like(self.variants[0].image, dtype=np.float64)
        for idx, w in zip(top_indices, weights):
            blended_img += float(w) * self.variants[idx].image.astype(np.float64)
        blended_img = np.clip(blended_img, 0, 255).astype(np.uint8)

        # Update hysteresis tracker using best index
        self._apply_hysteresis(scores)

        return best_face, blended_img

    # ------------------------------------------------------------------
    # Convenience: get embedding (possibly blended) for pipeline step 9
    # ------------------------------------------------------------------

    def get_embedding(
        self,
        frame: np.ndarray,
        detected_face,
        convert_fn=None,
    ) -> np.ndarray:
        """Return the per-frame source embedding ready for the swap model.

        Args:
            frame:          BGR webcam frame
            detected_face:  insightface Face object
            convert_fn:     optional function to convert embedding for the
                            swap backend (e.g. Ghost's _convert_embedding)

        Returns:
            512-d (or backend-specific) embedding numpy array.
        """
        if self.method == "blend":
            face_obj, _ = self.select_blended(frame, detected_face)
            emb = face_obj.normed_embedding
        else:
            variant = self.select(frame, detected_face)
            emb = variant.embedding

        if convert_fn is not None:
            emb = convert_fn(emb)
        return emb

    # ------------------------------------------------------------------
    # Status / diagnostics
    # ------------------------------------------------------------------

    def get_status(self) -> dict:
        """Return a dict suitable for overlay display."""
        idx = self._current_idx or 0
        v   = self.variants[idx] if self.variants else None
        return {
            "variant_idx":   idx,
            "variant_name":  v.filename if v else "—",
            "variant_yaw":   f"{v.pose_yaw:+.0f}°" if v else "—",
            "variant_temp":  f"{v.color_temperature:.0f}K" if v else "—",
            "num_variants":  len(self.variants),
            "method":        self.method,
        }


# ---------------------------------------------------------------------------
# __main__ — webcam dashboard demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    print("SourceFaceSelector dashboard")
    print("  Turn your head → selected variant follows")
    print("  Change room lighting → variant adapts")
    print("  Press 'q' to quit, 'b' to toggle blend mode")

    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__)))))

    try:
        from neural_swap import NeuralFaceSwapper
    except ImportError as e:
        print(f"[ERROR] {e}"); sys.exit(1)

    swap_path = "models/ghost_3_256.onnx"
    src_dir   = "source_faces"

    if not os.path.exists(swap_path):
        print(f"[ERROR] Swap model not found: {swap_path}"); sys.exit(1)
    if not os.path.isdir(src_dir):
        print(f"[ERROR] source_faces/ directory not found"); sys.exit(1)

    swapper  = NeuralFaceSwapper(model_path=swap_path, occlusion=False)
    selector = SourceFaceSelector(swapper, {"source_face_dir": src_dir})

    THUMB_SIZE = 80
    thumbs = [cv2.resize(v.image, (THUMB_SIZE, THUMB_SIZE)) for v in selector.variants]

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("[ERROR] Cannot open webcam"); sys.exit(1)

    blend_mode = [False]
    frame_times = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.flip(frame, 1)
        h, w = frame.shape[:2]

        display = frame.copy()
        faces = swapper.detect(frame)

        if faces:
            face = faces[0]
            t0 = time.perf_counter()
            if blend_mode[0]:
                _, _ = selector.select_blended(frame, face)
            else:
                selector.select(frame, face)
            dt = (time.perf_counter() - t0) * 1000.0
            frame_times.append(dt)
            if len(frame_times) > 60: frame_times.pop(0)

            # Draw face box
            x1, y1, x2, y2 = face.bbox.astype(int)
            cv2.rectangle(display, (x1, y1), (x2, y2), (0, 255, 0), 2)

            # Show estimated conditions
            yaw, pitch = selector.estimate_pose(face.kps)
            temp, ld, lum = selector.estimate_lighting(frame, face.bbox)
            st = selector.get_status()
            info = [
                f"Yaw: {yaw:+.0f} deg  Pitch: {pitch:+.0f} deg",
                f"Temp: {temp:.0f}K   Lum: {lum:.2f}",
                f"Light dir: ({ld[0]:+.2f}, {ld[1]:+.2f})",
                f"Selected: [{st['variant_idx']}] {st['variant_name']}",
                f"select time: {sum(frame_times)/len(frame_times):.2f}ms",
                f"Mode: {'BLEND' if blend_mode[0] else 'SELECT'} [b]=toggle",
            ]
            for i, line in enumerate(info):
                cv2.putText(display, line, (8, 22 + i * 20),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 0), 1)

        # Sidebar with variant thumbnails
        sidebar_w = THUMB_SIZE + 10
        n = len(thumbs)
        sidebar_h = max(h, n * (THUMB_SIZE + 4))
        sidebar = np.zeros((sidebar_h, sidebar_w, 3), dtype=np.uint8)
        cur = selector._current_idx or 0

        for i, thumb in enumerate(thumbs):
            y_off = i * (THUMB_SIZE + 4)
            sidebar[y_off:y_off + THUMB_SIZE, 5:5 + THUMB_SIZE] = thumb
            color = (0, 255, 0) if i == cur else (80, 80, 80)
            cv2.rectangle(sidebar, (5, y_off), (5 + THUMB_SIZE, y_off + THUMB_SIZE), color, 2)
            # Score label
            name = selector.variants[i].filename[:8]
            cv2.putText(sidebar, name, (5, y_off + THUMB_SIZE - 4),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.3, (200, 200, 200), 1)

        sidebar_cropped = sidebar[:h, :]
        display_h = min(h, display.shape[0])
        canvas = np.hstack([display[:display_h], sidebar_cropped[:display_h]])

        cv2.imshow("SourceFaceSelector", canvas)
        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
            break
        if key == ord("b"):
            blend_mode[0] = not blend_mode[0]

    cap.release()
    cv2.destroyAllWindows()
